{ pkgs, lib, modulesPath, ... }:

{
  networking.hostName = "benjaminedwardwebb-me";

  imports = [
    # For hardware configuration (generated by nixos-infect).
    (modulesPath + "/profiles/qemu-guest.nix")
    # Import system configuration specific to the application.
    ./application.nix
  ];

  boot.cleanTmpDir = true;
  zramSwap.enable = true;

  services.openssh.enable = true;
  services.openssh.passwordAuthentication = false;
  security.sudo.execWheelOnly = true;
  users.mutableUsers = true;
  users.users.root = { 
    openssh.authorizedKeys.keys = [
      # THESE ARE PUBLIC KEYS. THERE ARE NO SECRETS STORED IN THIS REPOSITORY.
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDwOMPY/v4CSSHFghLFi6i1aQ1Dh6jW2VjvZFM+ZAaYs63YUaXvqqX7XPxNFtxKCtGGCBGZo/VuS85sQeXHk4RD4aclzAB5ittH0max4GZOi6d0AtfuoUNZ0Ui3jJlDErcmqNCCgi6apZZJiO2c8ZwD+sRoF3jRflWw9bl+wX53z2IZ8wD5+EBhqZEL7X/Q7kHZmdgKsieee0KwrUgOUj82t1b5AK3A9yG3h045HUc5E7cwN3yHNSXjRZg2pbIp/bi+qMenW0UJ356+yRwrVPcR4VhuxHkBCqWoV2jI99tnTfpJA05H6Nepv6pPldKa+HDP+uNvfGJ9FZw+gUWviBAF benjaminedwardwebb"
    ];
  };
  users.users.benjaminedwardwebb = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    description = "Benjamin Edward Webb";
    openssh.authorizedKeys.keys = [
      # THESE ARE PUBLIC KEYS. THERE ARE NO SECRETS STORED IN THIS REPOSITORY.
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDwOMPY/v4CSSHFghLFi6i1aQ1Dh6jW2VjvZFM+ZAaYs63YUaXvqqX7XPxNFtxKCtGGCBGZo/VuS85sQeXHk4RD4aclzAB5ittH0max4GZOi6d0AtfuoUNZ0Ui3jJlDErcmqNCCgi6apZZJiO2c8ZwD+sRoF3jRflWw9bl+wX53z2IZ8wD5+EBhqZEL7X/Q7kHZmdgKsieee0KwrUgOUj82t1b5AK3A9yG3h045HUc5E7cwN3yHNSXjRZg2pbIp/bi+qMenW0UJ356+yRwrVPcR4VhuxHkBCqWoV2jI99tnTfpJA05H6Nepv6pPldKa+HDP+uNvfGJ9FZw+gUWviBAF benjaminedwardwebb"
    ];
  };
  # THERE ARE NO SECRETS STORED IN THIS REPOSITORY.
  #// import /etc/password.nix;

  environment.systemPackages = with pkgs; [
    vim
    curl
    git
  ];

  # Configure hardware (generated by nixos-infect).
  boot.loader.grub.device = "/dev/vda";
  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "xen_blkfront" ];
  boot.initrd.kernelModules = [ "nvme" ];
  fileSystems."/" = { device = "/dev/vda1"; fsType = "ext4"; };

  # Configure network (generated by nixos-infect).
  networking = {
    nameservers = [ "8.8.8.8" ];
    defaultGateway = "165.227.80.1";
    defaultGateway6 = "";
    dhcpcd.enable = false;
    usePredictableInterfaceNames = lib.mkForce false;
    interfaces = {
      eth0 = {
        ipv4.addresses = [
          { address = "165.227.83.137"; prefixLength = 20; }
          { address = "10.10.0.5"; prefixLength = 16; }
        ];
        ipv6.addresses = [
          { address = "fe80::8c16:51ff:fe77:bf53"; prefixLength = 64; }
        ];
        ipv4.routes = [
          { address = "165.227.80.1"; prefixLength = 32; }
        ];
        ipv6.routes = [
          { address = ""; prefixLength = 128; }
        ];
      };
    };
  };
  services.udev.extraRules = ''
    ATTR{address}=="8e:16:51:77:bf:53", NAME="eth0"
    ATTR{address}=="0a:8e:ef:86:40:fc", NAME="eth1"
  '';
}
